version: "3.9"

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    volumes:
      - data:/data
    env_file: ".env"
    ports:
      - "5432:5432"
    restart: always
